### PR TITLE
Remove BIP70 payment server protocol from tapyrus

### PR DESCRIPTION
**Pull request by Naviabheeman**
Cherry-picked commits from bitcoin-core disabling BIP70 and removed its new argument to configure script. 
Removed support to build and test payment server.

### CODE REVIEW

**Comment by Naviabheeman** [comment]
Please don't merge this yet. I noticed that send and receive tabs do not open correctly. I need to debug further

**Comment by azuchi** [comment]
> Please don't merge this yet. I noticed that send and receive tabs do not open correctly. I need to debug further

[WIP] was added to the title. Remove the [WIP] when you are finished.

**Comment by azuchi** [comment]
In addition to remove BIP70, can remote the OpenSSL dependency as well?

https://github.com/bitcoin/bitcoin/pull/17265

**Comment by Naviabheeman** [comment]
> In addition to remove BIP70, can remove the OpenSSL dependency as well?
> 
> [bitcoin/bitcoin#17265](https://github.com/bitcoin/bitcoin/pull/17265)

Should we include https://github.com/bitcoin/bitcoin/pull/10299 as well?

**Comment by azuchi** [comment]
> Should we include [bitcoin/bitcoin#10299](https://github.com/bitcoin/bitcoin/pull/10299) as well?

Actually, make this a separate task after all. You don't have to respond with this PR.

**Comment by Naviabheeman** [comment]
> `qt/paymentserver.h` and `qt/paymentserver.cpp` are still required?

The files are required as they have Signals and Slots to send and receive coins. I don't know the QT framework well enough to refactor these. But some other parts may be unnecessary. I'll try to remove them.

**Pull request merged**
