### PR TITLE
Task 1 PR3 Decode wallet transaction and store Token balance inside the wallet

### PR DESCRIPTION
**Pull request by winnie-chaintope**
Refering task : https://github.com/Naviabheeman/tapyrus-core/wiki/Colored-coin-support-in-Tapyrus-Wallet

In this PR we are trying to identify coloured coins belonging to the wallet at transaction level. This is reported using various get balance functions.

CWallet::GetLegacyBalance CWallet::GetAvailableBalance CWallet::GetBalance CWallet::GetUnconfirmedBalance CWallet::GetUnconfirmedWatchOnlyBalance CWallet::AvailableCoins ApproximateBestSubset

Each token transaction added to the node’s mempool will also be added to the wallet by CWallet::AddToWallet.

AcceptToMemoryPoolWorker -> TransactionAddedToMempool -> SyncTransaction -> AddToWalletIfInvolvingMe -> AddToWallet

Wherever we changed balance += x in PR 1 should be make colorid aware. Decode the colorid from the scriptpubkey. The implementation should be context sensitive, In case we want to report the balance of one of the coloured coins, filter and add only the matching outputs. ColorIdentifier cid = GetColorIdFromScript(scriptpubkey) if(cid == inputColorId) balance += x In case we are collecting all the balances, add it to the map: ColorIdentifier cid = GetColorIdFromScript(scriptpubkey) balance[cid[ += x

Unit tests:

Outputs of all the affected functions should be tested using transactions with colorid and without colorid. Add tests to ensure the balance map has the correct entries and balances when there are default and coloured outputs.

### CODE REVIEW

**Comment by azuchi** [comment]
@winnie-chaintope Please rebase this to distinguish it from merged PRs.

**Comment by rantan** [comment]
@winnie-chaintope 
In wallet_tests.cpp, I found a test case for `CWallet::GetBalance()` but I couldn't find tests for the below methods that are mentioned by Navia. Do we need to add test cases for the below method?

* CWallet::GetLegacyBalance 
* CWallet::GetAvailableBalance 
* CWallet::GetUnconfirmedBalance 
* CWallet::GetUnconfirmedWatchOnlyBalance 
* CWallet::AvailableCoins ApproximateBestSubset

**Comment by winnie-chaintope** [comment]
> @winnie-chaintope
> In wallet_tests.cpp, I found a test case for `CWallet::GetBalance()` but I couldn't find tests for the below methods that are mentioned by Navia. Do we need to add test cases for the below method?
> 
> * CWallet::GetLegacyBalance
> * CWallet::GetAvailableBalance
> * CWallet::GetUnconfirmedBalance
> * CWallet::GetUnconfirmedWatchOnlyBalance
> * CWallet::AvailableCoins ApproximateBestSubset

@rantan yes it can be added

**Comment by rantan** [comment]
Ok, I will try to add test cases for these.

**Comment by rantan** [comment]
This PR is taken over #108

**Pull request closed without merging**
